### ISSUE TITLE
When you close the tablet it places a over lay on screen 

### ISSUE THREAD

**Issue by Tanoshi-Shinto** [AminYabut/tabby#1]
Basically when a player open the tablet and they close it. they cannot do anything in the server until they rejoin. 

heres a gif https://gyazo.com/a2ca1a46f796d2bfa199d00a5e1242b9

Ill try and fix when i have time but you might beat me to it

**Comment by Tanoshi-Shinto** [comment]
An easy fix would be on button press esc or backspace set tablet start false should close it. cause at the moment its setting tablet start to true on first open and then never returns it back to false

**Comment by AminYabut** [comment]
I am unable to recreate your issue. Maybe another mod is interfering with it?  I'm testing on a clean installed server.

**Comment by Tanoshi-Shinto** [comment]
Ill look into it. it could possible be something with esx_phone

**Comment by AminYabut** [comment]
Very well might be, esx uses the native user interface as well.

**Comment by Tanoshi-Shinto** [comment]
Alright. fresh new server and fresh install of all of esx and tablet it seems to work. so imma look into stuff on the main server and see what could be causing the issue.

**Comment by AminYabut** [comment]
Okay great, if you could let me know what was causing the issue i can alert others on my post and try to find a fix. Thanks again

**Comment by Tanoshi-Shinto** [comment]
Alright so seems to have been the name of the folder. i had changed it so i would know what it was since i have a bunch of odd names. i changed it back to just tab and it seems to work fine.

**Comment by AminYabut** [comment]
Your very right. The name of the folder cant change because of the nui call backs.

**Comment by AminYabut** [comment]
May I close this issue?

**Comment by Tanoshi-Shinto** [comment]
Yeah thanks for trying to help
