### ISSUE TITLE
problem for put me web

### ISSUE THREAD

**Issue by akranaz** [AminYabut/tabby#12]
no run web iun tab     wwithe windows show

i put in opencad.html

```
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <style>
        body {
            overflow: hidden;
            margin: 0;
        }

        #opencad {
            width: 100%;
            height: 100%;
            overflow: auto;
        }
    </style>
    <!-- ADD YOUR CAD/MDT SITE ADDRESS HERE -->
    <iframe id="opencad" src="https://trello.com/"></iframe>
</body>

</html>
```

and in ui

`                        <li data-title="OpenCAD">
                            <a class="nav-myframe" href="html/opencad.html">
                                <i class="myicon material-icons">dashboard</i>
                            </a>
                        </li>`

**Comment by AminYabut** [comment]
Is it just showing a white screen?

**Comment by burqka** [comment]
If you try to add multiple websites, it just shows one website properly, others are blank.

**Comment by AminYabut** [comment]
No, you either have an issue in your code somewhere or you're trying to add sites that block iframe open the affected page in your browser press f 12 to check the console and find your issue.
