### ISSUE TITLE
Lock when closing the tablet

### ISSUE THREAD

**Issue by AncientDarkFire** [AminYabut/tabby#15]
When closing the tablet it is minimized, however, the character continues as if the tablet were open

**Comment by AminYabut** [comment]
Sounds like you changed the name of the mod.

**Comment by AncientDarkFire** [comment]
Could it be because the folder I have added a 1 at the end?

**Comment by AminYabut** [comment]
yeah its needs to be called the name it came with or the nui calls wont work right

**Comment by AncientDarkFire** [comment]
I will correct it, thank you

**Comment by AminYabut** [comment]
no problem

**Comment by AncientDarkFire** [comment]
Hello, I have removed the number that had in the name, currently it is called "tabby-master" but the problem persists

**Comment by AminYabut** [comment]
needs to be called tab

**Comment by AncientDarkFire** [comment]
Hello again, sorry for the inconvenience but I would appreciate if you could guide me a bit. I have the tablet working in its entirety, the problem was the 1 that I had added, what happens is that that 1 is placed since I have another script that uses this same as a base, therefore they have the same name, I have tried merge them unsuccessfully, is there any way I can rename the script? 
I really want to use this script which is much better, but what happens with the others is that it is a ready-made PDA but it does not allow me to add more content to it. I have tried to bring the html of that PDA to this script without I exist.
I would be immensely grateful if I could help out with her.

**Comment by AncientDarkFire** [comment]
Hello, after a long effort I have managed to combine both scripts, however, apparently it does not allow me to call the html page that I have from the ui.html, I imagine it is because both are designed to be the main starting html. Do you know if there is any way I can toggle the `ui_page "nui / ui.html"` from within the html itself?

> needs to be called tab
