### ISSUE TITLE
Doesn't work with local files ?

### ISSUE THREAD

**Issue by Alevhovic** [AminYabut/tabby#3]
Hello AminYabut ! Thanks for the amazing work :) 

I don't have access to my "localhost/website" (write php), and i use the "opencad.html" without modification except the <iframe> line... I try on many browser (chrome, firefox, ie) and it works, but on game i have the white screen... 

The 23 line : 
    <iframe id="opencad" src="http://localhost/paneluser"></iframe>

Like i say, when i open "opencad.html" on Chrome/FireFox/I.E it's work !
Any idea ?

**Comment by AminYabut** [comment]
We spoke about using the domain name and not localhost on discord correct?

**Comment by AminYabut** [comment]
I'm gonna close this issue and if you need further support please contact me again.
